apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: localhost/kafka-producer:1.0.0
          env:
            - name: kafka-password
              valueFrom:
                secretKeyRef:
                  name: kafka-user-passwords
                  key: client-passwords
