apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: localhost/kafka-consumer:1.0.0
          env:
            - name: kafka-password
              valueFrom:
                secretKeyRef:
                  name: kafka-user-passwords
                  key: client-passwords
